### PR TITLE
Fill simplified chinise in.

### PR DESCRIPTION
**Pull request by oimken**
Fill simplified chinise in.

### CODE REVIEW

**Comment by nWidart** [comment]
Thank you but could you send this to asgardcms/platform (branch 2.0)  please ? 

Thanks

**Comment by oimken** [comment]
Finished！You are welcome。 :)

**Comment by oimken** [comment]
but, menu, tag, translate's   language files  not found in   asgardcms/platform (branch 2.0)

**Comment by nWidart** [comment]
Menu is there, tag has probably on its own module.

**Comment by oimken** [comment]
Sorry, My bad，I ignore the whole Module folder in Platform, and put separate module clone in it on my local disk, so I did not notice that Platform contain this modules.... I will send the request later.

**Pull request closed without merging**
